// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtfh0EYD8Wdo6dnY135tLpOa88q8wuMaM',
    appId: '1:375002827398:web:2f623d21b77b4a32bcdf07',
    messagingSenderId: '375002827398',
    projectId: 'divinty-ebdce',
    authDomain: 'divinty-ebdce.firebaseapp.com',
    storageBucket: 'divinty-ebdce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDr7X_7cwS8n1MYHlbR3v0I62eKHszBeQ',
    appId: '1:375002827398:android:9ec3257bc007505cbcdf07',
    messagingSenderId: '375002827398',
    projectId: 'divinty-ebdce',
    storageBucket: 'divinty-ebdce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYM2CCqmjctUEiF6qmWGwzIzOybt_gaTU',
    appId: '1:375002827398:ios:28c4722685a54421bcdf07',
    messagingSenderId: '375002827398',
    projectId: 'divinty-ebdce',
    storageBucket: 'divinty-ebdce.firebasestorage.app',
    iosBundleId: 'com.example.flutterFireChat',
  );
}
